language: cpp
compiler: gcc
dist: bionic

# The available apt packages can be found here:
# https://packages.ubuntu.com/bionic/allpackages
addons:
  apt:
    packages:
      - libpetsc3.7
      - libgsl23

script:
 - pwd
 - env
 - which mpicc
 - which mpif90
 - which gfortran

# - ./tests/travis.sh
