language: cpp
compiler: gcc
dist: bionic

# The available apt packages can be found here:
# https://packages.ubuntu.com/bionic/allpackages
addons:
  apt:
    packages:
      - libpetsc3.7

script:
 - pwd
# - ./tests/travis.sh
